name: Report a bug
description: Create a bug report to help improve our robot code
title: "[BUG] (bug summary)"
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Please use please see our [documentation](https://docs.robotguide.click).

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug!**

        ## Before Reporting a Bug

        - Remeber to be respectful! We are humans too :). Your help in providing detailed information will help us provide the best possible robot code!

        - Test with the latest version of the code ([How do I find this?](https://docs.robotguide.click)).

        ## Instructions

        Please follow the instructions below. Failure to do so may result in your issue being closed.

        1. Provide a good title starting with [BUG].
        2. Fill out all sections of this bug report form.
        3. Always attach additional files so we can replicate and test your setup.

  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
      placeholder: |
        Marlin doesn't work.
    validations:
      required: true

  - type: input
    attributes:
      label: Bug Timeline
      description: Is this a new bug or an old issue? When did it first start?

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: input
    attributes:
      label: Version of Marlin Firmware
      description: "See the About Menu on the LCD or the output of `M115`. NOTE: For older releases we only patch critical bugs."
    validations:
      required: true

  - type: input
    attributes:
      label: Printer model
      description: Creality Ender 3, Prusa mini, or Kossel Delta?

  - type: input
    attributes:
      label: Electronics
      description: Stock electronics, upgrade board, or something else?

  - type: input
    attributes:
      label: Add-ons
      description: Please list any hardware add-ons that could be involved.

  - type: dropdown
    attributes:
      label: Bed Leveling
      description: What kind of bed leveling compensation are you using?
      options:
        - UBL Bilinear mesh
        - ABL Bilinear mesh
        - ABL Linear grid
        - ABL 3-point
        - MBL Manual Bed Leveling
        - No Bed Leveling

  - type: dropdown
    attributes:
      label: Your Slicer
      description: Do you use Slic3r, Prusa Slicer, Simplify3D, IdeaMaker...?
      options:
        - Slic3r
        - Simplify3D
        - Prusa Slicer
        - IdeaMaker
        - Cura
        - Other (explain below)

  - type: dropdown
    attributes:
      label: Host Software
      description: Do you use OctoPrint, Repetier Host, Pronterface...?
      options:
        - SD Card (headless)
        - Repetier Host
        - OctoPrint
        - Pronterface
        - Cura
        - Same as my slicer
        - Other (explain below)

  - type: markdown
    attributes:
      value: |
        # Attachments

  - type: checkboxes
    attributes:
      label: Don't forget to include
      options:
        - label: A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
          required: true

  - type: markdown
    attributes:
      value: |
        ### Optional items to include:
        - 'Log output from the host. (`M111 S247` for maximum logging.)'
        - Images or videos demonstrating the problem, if it helps to make it clear.
        - A G-Code file that exposes the problem, if not affecting _all_ G-code.

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        If you've made any other modifications to the firmware, please describe them in detail.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.