name: Report a bug
description: Create a bug report to help improve our robot code
title: "[BUG] (bug summary)"
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Please use please see our [documentation](https://docs.robotguide.click).

  - type: input
    attributes:
      label: Name
      description: Please enter your name

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug!**

        ## Before Reporting a Bug

        - Remeber to be respectful! We are humans too :). Your help in providing detailed information will help us provide the best possible robot code!

        - Test with the latest version of the code ([How do I find this?](https://docs.robotguide.click)).

        ## Instructions

        Please follow the instructions below. Failure to do so may result in your issue being closed.

        1. Provide a good title starting with [BUG].
        2. Fill out all sections of this bug report form.
        3. Always attach additional files so we can replicate and test your setup.

  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.
      placeholder: |
        When I tried to drive the robot last saturday (28th), the robot started driving fowards instead of backwards. I tried multiple joysticks to no avial. There was a code that appeared on the dashboard, ERROR201 if that helps.
    validations:
      required: true

  - type: input
    attributes:
      label: Bug Timeline
      description: Is this a new bug or an old issue? When did it first start?
      placeholder: |
        Last saturday (28th)

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen? What actually happened
      placeholder: I expected it to move foward, but the direction was inverted.

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...

  - type: input
    attributes:
      label: Version of software
      description: "See above for retriving software version"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Dashboard
      description: Are you using SmartDashboard, Shuffleboard, etc...?
      options:
        - SmartDashboard
        - Shuffleboard
        - LabView dahsboard
        - Other (explain below)
        - I don't know

  - type: dropdown
    attributes:
      label: Importance
      description: How important is this bug to fix?
      options:
        - Low (eg. LEDs don't work)
        - Medium (eg. drivers need a button swapped)
        - High (eg. part of the robot is not quite working properly)
        - Critical (eg. part of the robot is completly non-functional and comp is tomorrow.)

  - type: markdown
    attributes:
      value: |
        # Attachments

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        Please upload any additional relevant files